### ISSUE TITLE
The version and build number is not being changed when adding a new target for iOS.

### ISSUE THREAD

**Issue by ilenin** [LucasMonteiro1/react-native-version-update#1]
**GENERAL**

1. In our organization, we created a more target for iOS with a "ShareMenuExtension" name, but the version and build of this new target for iOS aren't being changed.

> ![Screen Shot 2021-11-14 at 14 02 48](https://user-images.githubusercontent.com/62823368/141690703-8545fba3-794d-4a3d-a454-6870bf267e12.png)

**Comment by LucasMonteiro1** [comment]
Version 0.3.0 published. 

[![NPM](https://nodei.co/npm/react-native-version-update.png?mini=true)](https://nodei.co/npm/react-native-version-update/)
